// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg2bmkkd-buV9srMlkPRsdsDCZGW4XGcs',
    appId: '1:257337623722:web:649cd17fffd76226c03cd3',
    messagingSenderId: '257337623722',
    projectId: 'petapp-99fad',
    authDomain: 'petapp-99fad.firebaseapp.com',
    storageBucket: 'petapp-99fad.firebasestorage.app',
    measurementId: 'G-786ZGE2163',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2DfScBosJSjKPpykso-1gMt7bPiiksjI',
    appId: '1:257337623722:android:54039404ccd2fe99c03cd3',
    messagingSenderId: '257337623722',
    projectId: 'petapp-99fad',
    storageBucket: 'petapp-99fad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFy_Boh4DJ8bm5bkBMzAZBaT7GDbqW6kc',
    appId: '1:257337623722:ios:95e85a3a49a610d8c03cd3',
    messagingSenderId: '257337623722',
    projectId: 'petapp-99fad',
    storageBucket: 'petapp-99fad.firebasestorage.app',
    iosBundleId: 'com.example.livestockRecordAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFy_Boh4DJ8bm5bkBMzAZBaT7GDbqW6kc',
    appId: '1:257337623722:ios:95e85a3a49a610d8c03cd3',
    messagingSenderId: '257337623722',
    projectId: 'petapp-99fad',
    storageBucket: 'petapp-99fad.firebasestorage.app',
    iosBundleId: 'com.example.livestockRecordAppNew',
  );
}
